### ISSUE TITLE
Pretrain

### ISSUE THREAD

**Issue by libing125** [thunlp/ERNIE#37]
How to pretrain the model? I run 

python3 code/run_pretrain.py --do_train --data_dir pretrain_data/ --bert_model ernie_base --output_dir pretrain_out/ --task_name pretrain --fp16

but get error message

Traceback (most recent call last):
  File "code/run_pretrain.py", line 423, in <module>
    main()
  File "code/run_pretrain.py", line 320, in main
    loss, original_loss = model(input_ids, segment_ids, input_mask, masked_lm_labels, input_ent.half(), ent_mask, next_sentence_label, ent_candidate.half(), ent_labels)
  File ".local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "ERNIE/code/knowledge_bert/modeling.py", line 839, in forward
    next_sentence_loss = loss_fct(seq_relationship_score.view(-1, 2), next_sentence_label.view(-1))
  File "local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File ".local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "local/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "local/lib/python3.6/site-packages/torch/nn/functional.py", line 1869, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (32) to match target batch_size (24608).

Where the value 24608 comes from? How can I run pretraining? Thanks.

**Comment by zzy14** [comment]
Sorry for the missing detail. You need to set the max-seq-len as 256 while the default value is 128. Try this command `python3 code/run_pretrain.py --do_train --data_dir pretrain_data/sample --bert_model ernie_base --output_dir pretrain_out/ --task_name pretrain --fp16 --max_seq_length 256`.

**Comment by libing125** [comment]
It works. Thank you!
