### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: .......ERNIE-master\\<input>'

### ISSUE THREAD

**Issue by twin9458** [thunlp/ERNIE#81]
### **I'm so sad .....

Now I'm running the file 'pretrain_data/create_ids.py'
However, there is an error that there is no information about <input>
What do you think was the reason?**

**In my code, my directory root is as follows:**
vocab_file = "G:/내 드라이브/[LAB 01]_개인 연구/04. Pilot 분석/ERNIE/ERNIE-master/ERNIE-master/ernie_base/ernie_base/vocab.txt"
do_lower_case = True
input_folder = "G:/내 드라이브/[LAB 01]_개인 연구/04. Pilot 분석/ERNIE/ERNIE-master/ERNIE-master/pretrain_data/ann"

**And my error message is as follows :**
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\내 드라이브\\[LAB 01]_개인 연구\\04. Pilot 분석\\ERNIE\\ERNIE-master\\ERNIE-master\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 114, in _main
    exitcode = _main(fd)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\anaconda\envs\Python3.6\lib\runpy.py", line 261, in run_path
    exitcode = _main(fd)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 114, in _main
    run_name="__mp_main__")
  File "C:\anaconda\envs\Python3.6\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\anaconda\envs\Python3.6\lib\runpy.py", line 231, in _get_code_from_file
    prepare(preparation_data)
  File "C:\anaconda\envs\Python3.6\lib\multiprocessing\spawn.py", line 225, in prepare
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\anaconda\envs\Python3.6\lib\runpy.py", line 231, in _get_code_from_file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    with open(fname, "rb") as f:

**Only raw folders are created, and data files are not created in them**

**Comment by zzy14** [comment]
Hi,

It looks like the path is wrong. "ERNIE-master" repeats twice in "G:\내 드라이브\[LAB 01]_개인 연구\04. Pilot 분석\ERNIE\ERNIE-master\ERNIE-master\". Try using "G:\내 드라이브\[LAB 01]_개인 연구\04. Pilot 분석\ERNIE\ERNIE-master\" instead.
